### ISSUE TITLE
Could not load 'plugins/GemsEconomy-4.9.2.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Ellinikor** [Xanium1/GemsEconomy#13]
It is impossible to use gemseconomy in 1.16 because the following error message appears:

[Server thread/ERROR]: Could not load 'plugins/GemsEconomy-4.9.2.jar' in folder 'plugins'

org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml

	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:170) ~[patched_1.16.4.jar:git-Paper-319]

	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:148) ~[patched_1.16.4.jar:git-Paper-319]

	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:389) ~[patched_1.16.4.jar:git-Paper-319]

	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:206) ~[patched_1.16.4.jar:git-Paper-319]

	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:936) ~[patched_1.16.4.jar:git-Paper-319]

	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:178) ~[patched_1.16.4.jar:git-Paper-319]

	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]

Caused by: java.util.zip.ZipException: zip file is empty

	at java.util.zip.ZipFile.open(Native Method) ~[?:1.8.0_251]

	at java.util.zip.ZipFile.<init>(ZipFile.java:225) ~[?:1.8.0_251]

	at java.util.zip.ZipFile.<init>(ZipFile.java:155) ~[?:1.8.0_251]

	at java.util.jar.JarFile.<init>(JarFile.java:167) ~[?:1.8.0_251]

	at java.util.jar.JarFile.<init>(JarFile.java:131) ~[?:1.8.0_251]

	at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:158) ~[patched_1.16.4.jar:git-Paper-319]

	... 6 more

**Comment by untuned** [comment]
Do you have to upload files using FTP/SFTP? If so, the file probably got corrupted as you were uploading it. Just try again.

**Comment by Ellinikor** [comment]
Oh thx, it's done. And I've an other question; your plugin is compatible with Towny and Chest Shop because when I used that, Towny don't know the money in the bank of cities, and Chest Shops have an error, and I enabled Vault in the  config.
