### ISSUE TITLE
[BUG] MySQL Host not being set properly

### ISSUE THREAD

**Issue by untuned** [Xanium1/GemsEconomy#14]
I have my MySQL host set to a server, let's name it DBServer. The Minecraft is hosted on a different server, say MCServer.

This is the error I get in chat:
```
[11:24:53 INFO]: [GemsEconomy] Enabling GemsEconomy v4.9.2
[11:24:53 INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-2 - Starting...
[11:24:54 ERROR]: [com.zaxxer.hikari.pool.HikariPool] HikariPool-2 - Exception during pool initialization.
java.sql.SQLException: Access denied for user 'sc_currency'@'MCServer-IP' (using password: YES)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:833) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[?:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[?:?]
        at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at me.xanium.gemseconomy.data.MySQLStorage.initialize(MySQLStorage.java:78) ~[?:?]
        at me.xanium.gemseconomy.GemsEconomy.initializeDataStore(GemsEconomy.java:165) ~[?:?]
        at me.xanium.gemseconomy.GemsEconomy.onEnable(GemsEconomy.java:103) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:271) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1071) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:292) ~[patched_1.16.5.jar:git-Tuinity-"f32fe9a"]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

Despite the correct IP being given in the config, it is not using that IP. It is instead using the local server's given IP address.

**Comment by samuelh2005** [comment]
On the [main spigot page](https://www.spigotmc.org/resources/gemseconomy.19655/) it says this mod is "DISCONTINUED". However I have found https://github.com/ArcanePlugins/Polyconomy and https://github.com/ArcanePlugins/Treasury (to be used together) which offer similar features to GemsEconomy.
