### ISSUE TITLE
Issue loading plugin in 1.14.4

### ISSUE THREAD

**Issue by whostroll** [Xanium1/GemsEconomy#19]
I was planning to add multiple economies in my skyblock server, the plugin wont load and only this show up in console

```
[11:43:30 ERROR]: Could not load 'plugins\GemsEconomy-4.9.2.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.16
        at org.bukkit.craftbukkit.v1_14_R1.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:261) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257) ~[patched_1.14.4.jar:git-Paper-243]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:355) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:226) ~[patched_1.14.4.jar:git-Paper-243]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-243]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

        
The plugin itself works in 1.12.2 but not 1.14.4

**Comment by whostroll** [comment]
Fix:

Edit the API version in plugin.yml to 1.14
