### ISSUE TITLE
Plugin cannot create account in MySQL database.

### ISSUE THREAD

**Issue by blan4e** [Xanium1/GemsEconomy#2]
`[17:31:41] [WARN]: java.sql.SQLException: No value specified for parameter 4

[17:31:41] [WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)

[17:31:41] [WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)

[17:31:41] [WARN]: 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)

[17:31:41] WARN]: 	        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)

[17:31:41] [WARN]: 	at com.mysql.jdbc.PreparedStatement.checkAllParametersSet(PreparedStatement.java:2268)

[17:31:41] [WARN]: 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2248)

[17:31:41] [WARN]: 	at com.mysql.jdbc.PreparedStatement.fillSendPacket(PreparedStatement.java:2178)

[17:31:41] [WARN]: 	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1219)

[17:31:41] [WARN]: 	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)

[17:31:41] [WARN]: 	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)

[17:31:41] [WARN]: 	at me.xanium.gemseconomy.data.MySQLStorage.createAccount(MySQLStorage.java:324)

[17:31:41] [WARN]: 	at me.xanium.gemseconomy.listeners.EconomyListener.lambda$onLogin$0(EconomyListener.java:39)

[17:31:41] [WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99)

[17:31:41] [WARN]: 	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)

[17:31:41] [WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)

[17:31:41] [WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)

[17:31:41] [WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)

[17:31:41] [WARN]: 	at java.base/java.lang.Thread.run(Thread.java:832)
`

**PaperSpiot 1.16.4, MySQL server version: 10.5.8-MariaDB - Arch Linux**

**Comment by Xanium1** [comment]
I am looking into this right now.

**Comment by Aeris1One** [comment]
Same : 
![image](https://user-images.githubusercontent.com/29739547/103227395-927e3500-492e-11eb-9c04-a292c462957f.png)

And because of the account not being created, this pop-up every time a player connects. Also /balance returns that "The specified player doesn't exists".

EDIT : Is this fixed by #3 ?
