### ISSUE TITLE
I have a error with my plugin in 1.19.3

### ISSUE THREAD

**Issue by Chrqmated** [Xanium1/GemsEconomy#21]
[18:48:53] [Craft Scheduler Thread - 91 - GemsEconomy/WARN]: [GemsEconomy] Plugin GemsEconomy v4.9.3-GCRemake-1.6 generated an exception while executing task 152585
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at me.xanium.gemseconomy.account.AccountManager.getAccount(AccountManager.java:74) ~[GemsEconomy-4.9.3-GCRemake-1.6.jar:?]
	at me.xanium.gemseconomy.listeners.EconomyListener.lambda$onLogin$0(EconomyListener.java:33) ~[GemsEconomy-4.9.3-GCRemake-1.6.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.19.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by samuelh2005** [comment]
On the [main spigot page](https://www.spigotmc.org/resources/gemseconomy.19655/) it says this mod is "DISCONTINUED". However I have found https://github.com/ArcanePlugins/Polyconomy and https://github.com/ArcanePlugins/Treasury (to be used together) which offer similar features to GemsEconomy.
